class AppStates {}
class AppInitialPageState extends AppStates{}
class AppBottomNavBarState extends AppStates{}
class AppLoadingState extends AppStates{}
class AppHomeSuccessDataState extends AppStates{}
class AppHomeErrorDataState extends AppStates{}
class AppCategorieSuccessDataState extends AppStates{}
class AppCategorieErrorDataState extends AppStates{}
class AppFavouriteChangeState extends AppStates{}
class AppFavouriteSuccessState extends AppStates{}
class AppFavouriteErrorState extends AppStates{}
class AppGetFavouriteLoadingState extends AppStates{}
class AppGetFavouriteSuccessState extends AppStates{}
class AppGetFavouriteErrorState extends AppStates{}
class AppGetProfileLoadingState extends AppStates{}
class AppGetProfileSuccessState extends AppStates{}
class AppGetProfileErrorState extends AppStates{}
class AppUpdateProfileLoadingState extends AppStates{}
class AppUpdateProfileSuccessState extends AppStates{}
class AppUpdateProfileErrorState extends AppStates{}
class AppGetSearchLoadingState extends AppStates{}
class AppGetSearchSuccessState extends AppStates{}
class AppGetSearchErrorState extends AppStates{}